name: Deploy

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [update-event]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v3

      - name: Clone Repository B
        run: |
          cd ${{ github.workspace }}
          git clone https://github.com/mingriyingying/zjc_notes.git temp-repo

      - name: Copy Repository B to Folder in Repository A
        run: |
          cd ${{ github.workspace }}
          rm -rf docs/articles/*
          mv temp-repo/articles/* docs/articles/

      - name: Setup Node.js (yarn)
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      
      - name: Yarn Install
        run: yarn install --frozen-lockfile

      - name: Yarn Build
        run: yarn build

      - name: Deploy to Branch gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
