name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository A
        run: git clone https://github.com/mingriyingying/mingriyingying.github.io.git

      - name: Clone Repository B
        run: git clone https://github.com/mingriyingying/zjc_notes.git temp-repo

      - name: Copy Repository B to Folder in Repository A
        run: |
          pwd
          ls
          rm -rf mingriyingying.github.io/docs/articles/*
          mv temp-repo/articles/* mingriyingying.github.io/docs/articles/

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
